##########################################################################
# Title:         Saltbox: Beszel-Agent | Default Variables               #
# Author(s):     f4bio                                                   #
# URL:           https://github.com/saltyorg/Saltbox                     #
# --                                                                     #
##########################################################################
#                   GNU General Public License v3.0                      #
##########################################################################
---
################################
# Basics
################################

beszel_agent_instances: ["beszel-agent"]

################################
# Paths
################################

beszel_agent_paths_folder: "{{ beszel_agent_name }}"
beszel_agent_paths_location: "{{ server_appdata_path }}/{{ beszel_agent_paths_folder }}"
beszel_agent_paths_folders_list:
  - "{{ beszel_agent_paths_location }}"

################################
# Docker
################################

# Container
beszel_agent_docker_container: "{{ beszel_agent_name }}"

# Image
beszel_agent_docker_image_pull: true
beszel_agent_docker_image_tag: "alpine"
beszel_agent_docker_image_repo: "beszel-agent"
beszel_agent_docker_image: "{{ lookup('vars', beszel_agent_name + '_docker_image_repo', default=beszel_agent_docker_image_repo) }}:{{ lookup('vars', beszel_agent_name + '_docker_image_tag', default=beszel_agent_docker_image_tag) }}"

# Ports
beszel_agent_docker_ports_defaults: []
beszel_agent_docker_ports_custom: []
beszel_agent_docker_ports: "{{ lookup('vars', beszel_agent_name + '_docker_ports_defaults', default=beszel_agent_docker_ports_defaults)
                        + lookup('vars', beszel_agent_name + '_docker_ports_custom', default=beszel_agent_docker_ports_custom) }}"

# Envs
beszel_agent_docker_envs_default:
  TZ: "{{ tz }}"
beszel_agent_docker_envs_custom: {}
beszel_agent_docker_envs: "{{ lookup('vars', beszel_agent_name + '_', default=beszel_agent_docker_envs_default)
                       | combine(lookup('vars', beszel_agent_name + '_docker_envs_custom', default=beszel_agent_docker_envs_custom)) }}"

# Commands
beszel_agent_docker_commands_default: []
beszel_agent_docker_commands_custom: []
beszel_agent_docker_commands: "{{ lookup('vars', beszel_agent_name + '_docker_commands_default', default=beszel_agent_docker_commands_default)
                           + lookup('vars', beszel_agent_name + '_docker_commands_custom', default=beszel_agent_docker_commands_custom) }}"

# Volumes
beszel_agent_docker_volumes_default:
  - "{{ beszel_agent_paths_location }}:/data"
beszel_agent_docker_volumes_custom: []
beszel_agent_docker_volumes: "{{ lookup('vars', beszel_agent_name + '_docker_volumes_default', default=beszel_agent_docker_volumes_default)
                          + lookup('vars', beszel_agent_name + '_docker_volumes_custom', default=beszel_agent_docker_volumes_custom) }}"

# Devices
beszel_agent_docker_devices_default: []
beszel_agent_docker_devices_custom: []
beszel_agent_docker_devices: "{{ lookup('vars', beszel_agent_name + '_docker_devices_default', default=beszel_agent_docker_devices_default)
                          + lookup('vars', beszel_agent_name + '_docker_devices_custom', default=beszel_agent_docker_devices_custom) }}"

# Hosts
beszel_agent_docker_hosts_default: {}
beszel_agent_docker_hosts_custom: {}
beszel_agent_docker_hosts: "{{ docker_hosts_common
                        | combine(lookup('vars', beszel_agent_name + '_docker_hosts_default', default=beszel_agent_docker_hosts_default))
                        | combine(lookup('vars', beszel_agent_name + '_docker_hosts_custom', default=beszel_agent_docker_hosts_custom)) }}"

# Labels
beszel_agent_docker_labels_default: {}
beszel_agent_docker_labels_custom: {}
beszel_agent_docker_labels: "{{ docker_labels_common
                         | combine(lookup('vars', beszel_agent_name + '_docker_labels_default', default=beszel_agent_docker_labels_default))
                         | combine(lookup('vars', beszel_agent_name + '_docker_labels_custom', default=beszel_agent_docker_labels_custom)) }}"

# Hostname
beszel_agent_docker_hostname: "{{ beszel_agent_name }}"

# Network Mode
beszel_agent_docker_network_mode_default: "{{ docker_networks_name_common }}"
beszel_agent_docker_network_mode: "{{ lookup('vars', beszel_agent_name + '_docker_network_mode_default', default=beszel_agent_docker_network_mode_default) }}"

# Networks
beszel_agent_docker_networks_alias: "{{ beszel_agent_name }}"
beszel_agent_docker_networks_default: []
beszel_agent_docker_networks_custom: []
beszel_agent_docker_networks: "{{ docker_networks_common
                           + lookup('vars', beszel_agent_name + '_docker_networks_default', default=beszel_agent_docker_networks_default)
                           + lookup('vars', beszel_agent_name + '_docker_networks_custom', default=beszel_agent_docker_networks_custom) }}"

# Capabilities
beszel_agent_docker_capabilities_default: []
beszel_agent_docker_capabilities_custom: []
beszel_agent_docker_capabilities: "{{ lookup('vars', beszel_agent_name + '_docker_capabilities_default', default=beszel_agent_docker_capabilities_default)
                               + lookup('vars', beszel_agent_name + '_docker_capabilities_custom', default=beszel_agent_docker_capabilities_custom) }}"

# Security Opts
beszel_agent_docker_security_opts_default: []
beszel_agent_docker_security_opts_custom: []
beszel_agent_docker_security_opts: "{{ lookup('vars', beszel_agent_name + '_docker_security_opts_default', default=beszel_agent_docker_security_opts_default)
                                + lookup('vars', beszel_agent_name + '_docker_security_opts_custom', default=beszel_agent_docker_security_opts_custom) }}"

# Restart Policy
beszel_agent_docker_restart_policy: unless-stopped

# State
beszel_agent_docker_state: started

# User
beszel_agent_docker_user: "{{ uid }}:{{ gid }}"
