#########################################################################
# Title:            Sandbox: Beszel                                     #
# Author(s):        f4bio                                               #
# URL:              https://github.com/saltyorg/Sandbox                 #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Add DNS record
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/dns/tasker.yml"
  vars:
    dns_record: "{{ lookup('vars', role_name + '_dns_record') }}"
    dns_zone: "{{ lookup('vars', role_name + '_dns_zone') }}"
    dns_proxy: "{{ lookup('vars', role_name + '_dns_proxy') }}"

- name: Remove existing Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/remove_docker_container.yml"

- name: Create directories
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/directories/create_directories.yml"

- name: Create Docker container
  ansible.builtin.include_tasks: "{{ resources_tasks_path }}/docker/create_docker_container.yml"

- name: "Import Agent Role"
  ansible.builtin.include_role:
    name: beszel-agent
  vars:
    beszel_agent: ["beszel-agent"]

- name: Prompt for user to input agent token
  ansible.builtin.pause:
    prompt: "Go to Beszel Hub, add new system and enter the token displayed (e.g., 'a1564dba-9d64-4be4-94ad-f209e9dd733f')"
  register: agent_token

- name: Prompt for user to input 
  ansible.builtin.pause:
    prompt: "...and the corresponding agent key (e.g., 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIC2YufokpaoKXT5mimcuu0JdfWadErOGAC6hn8+yB5D+')"
  register: agent_key